/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PastWorkRouteImport } from './routes/past-work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PastWorkSlugRouteImport } from './routes/past-work.$slug'

const PastWorkRoute = PastWorkRouteImport.update({
  id: '/past-work',
  path: '/past-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PastWorkSlugRoute = PastWorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PastWorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/past-work': typeof PastWorkRouteWithChildren
  '/past-work/$slug': typeof PastWorkSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/past-work': typeof PastWorkRouteWithChildren
  '/past-work/$slug': typeof PastWorkSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/past-work': typeof PastWorkRouteWithChildren
  '/past-work/$slug': typeof PastWorkSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/past-work' | '/past-work/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/past-work' | '/past-work/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/past-work'
    | '/past-work/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PastWorkRoute: typeof PastWorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/past-work': {
      id: '/past-work'
      path: '/past-work'
      fullPath: '/past-work'
      preLoaderRoute: typeof PastWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-work/$slug': {
      id: '/past-work/$slug'
      path: '/$slug'
      fullPath: '/past-work/$slug'
      preLoaderRoute: typeof PastWorkSlugRouteImport
      parentRoute: typeof PastWorkRoute
    }
  }
}

interface PastWorkRouteChildren {
  PastWorkSlugRoute: typeof PastWorkSlugRoute
}

const PastWorkRouteChildren: PastWorkRouteChildren = {
  PastWorkSlugRoute: PastWorkSlugRoute,
}

const PastWorkRouteWithChildren = PastWorkRoute._addFileChildren(
  PastWorkRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PastWorkRoute: PastWorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
